### ISSUE TITLE
easy_connect.py for Bombsquad 1.7.7 is broken

### ISSUE THREAD

**Issue by rikkolovescats** [bombsquad-community/plugin-manager#39]
[easy_connect.py](https://github.com/bombsquad-community/plugin-manager/blob/fc6134855759f44715672df192e06ff17bd8440c/plugins/utilities/easy_connect.py) is broken on 1.7.7.

This error when opening the public party list with the plugin enabled:
```python
line 298, in update
    ping_good = _ba.get_v1_account_misc_read_val('pingGood', 100)
AttributeError: module '_ba' has no attribute 'get_v1_account_misc_read_val'
```

We need to update this plugin. It'd be good idea to make the update backwards compatible so it works on game versions lower than 1.7.7 as well. Check out [colorscheme v1.2.2 update](https://github.com/bombsquad-community/plugin-manager/commit/a6d1a435c9f87a9dbbb4c86a3df57a247b0a88ff) for an example.
