### PR TITLE
fixed easy connect for 1.7.7

### LINKED ISSUE #39: easy_connect.py for Bombsquad 1.7.7 is broken
[easy_connect.py](https://github.com/bombsquad-community/plugin-manager/blob/fc6134855759f44715672df192e06ff17bd8440c/plugins/utilities/easy_connect.py) is broken on 1.7.7.

This error when opening the public party list with the plugin enabled:
```python
line 298, in update
    ping_good = _ba.get_v1_account_misc_read_val('pingGood', 100)
AttributeError: module '_ba' has no attribute 'get_v1_account_misc_read_val'
```

We need to update this plugin. It'd be good idea to make the update backwards compatible so it works on game versions lower than 1.7.7 as well. Check out [colorscheme v1.2.2 update](https://github.com/bombsquad-community/plugin-manager/commit/a6d1a435c9f87a9dbbb4c86a3df57a247b0a88ff) for an example.

### PR DESCRIPTION
**Pull request by CrossJoy**
Closes #39

### CODE REVIEW

File: plugins/utilities/easy_connect.py [hunk 1]
```diff
@@ -458,7 +458,23 @@ def popup_menu_selected_choice(self, window: popup.PopupMenu,
...
+    version = tuple(map(int, version.split(".")))
+    return game_version < version
+
+
 def replace():
+    global ba_internal
+    if is_game_version_lower_than("1.7.7"):
+        ba_internal = _ba
+    else:
+        ba_internal = ba.internal
```
Comment (rikkolovescats) [inline plugins/utilities/easy_connect.py:477]: I think a more readable way would be to define this at the top instead of declaring a global variable here.

File: plugins/utilities.json [hunk 2]
```diff
@@ -119,6 +119,12 @@
         }
       ],
       "versions": {
+        "1.2.0": {
```
Comment (rikkolovescats) [inline plugins/utilities.json:122]: Is there a reason this change is versioned as `1.2.0` (instead of `1.1.0`)?

**Review by rikkolovescats — CHANGES_REQUESTED** [review]
Thanks! I left a few review comments. Happy to merge once they are addressed.

File: plugins/utilities.json (hunk 2 above)
Comment (vishal332008) [reply plugins/utilities.json:122]: Check the file , it is written version 1.2 , so I think it is fine to update this mod.

File: plugins/utilities/easy_connect.py (hunk 1 above)
Comment (CrossJoy) [reply plugins/utilities/easy_connect.py:477]: ok sure, I will make the changes soon.

**Review by rikkolovescats — APPROVED** [review]
Thanks again!
