### PR TITLE
Fix file_share.py

### PR DESCRIPTION
**Pull request by Freaku17**
Fixes the following error:
`  File "/storage/emulated/0/Android/data/net.froemling.bombsquad/files/mods/file_share.py", line 36, in <module>
    MODS_DIR = app.python_directory_user
               ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'App' object has no attribute 'python_directory_user'`

### CODE REVIEW

**Comment by Loup-Garou911XD** [comment]
While you are at it,can you also update discord rp plugin

**Review by Loup-Garou911XD — APPROVED** [review]
approved!!!

**Comment by Freaku17** [comment]
Okay

File: plugins/utilities/file_share.py [hunk 1]
```diff
@@ -33,7 +33,7 @@
 
 app = _babase.app
 
-MODS_DIR = app.python_directory_user
+MODS_DIR = app.env.python_directory_user
```
Comment (rikkolovescats) [inline plugins/utilities/file_share.py:36]: can we keep it so it also works on older 1.7 versions? otherwise it might not be nice to have some plugins only work with the latest 1.7.x versions and other plugins working only for the earlier 1.7.x versions.

looks like this breaking api change was made in build 21282:
https://github.com/efroemling/ballistica/blob/master/CHANGELOG.md#1727-build-21282-api-8-2023-08-30

Comment (rikkolovescats) [inline plugins/utilities/file_share.py:36]: can we keep it so it also works on older 1.7 versions? otherwise it might not be nice to have some plugins only work with the latest 1.7.x versions and other plugins working only for the earlier 1.7.x versions.

looks like old api was [deprecated in build 21282](https://github.com/efroemling/ballistica/blob/master/CHANGELOG.md#1727-build-21282-api-8-2023-08-30), so could be nice to call the newer api method only when client is on a build number after the deprecation happened (can be checked using `ba.env.TARGET_BALLISTICA_BUILD` me thinkypies!).

Comment (Freaku17) [reply plugins/utilities/file_share.py]: Done.
